### ISSUE TITLE
no class XposedHelprs

### ISSUE THREAD

**Issue by NoName1510** [Aliucord/hook#7]
When is it supported?

**Comment by rushiiMachine** [comment]
> Please note that this is only a partial implementation of Xposed, since we only need method hooking. Thus, only XposedBridge and hook classes are implemented. If you need the rest, just copy paste it from original Xposed and it should work with almost no modificiations.

This is a minimal wrapper over LSPlant
if you want the full API, consider using LSPatch or implement it yourself

**Comment by huygm1510** [comment]
I'm really sorry but I tried adding them and got an error so could you please add them for me?

**Comment by Vendicated** [comment]
![image](https://github.com/Aliucord/hook/assets/45497981/9835a43e-e0cb-43f0-b64b-d14383c74294)
