### ISSUE TITLE
please add loadModule function

### ISSUE THREAD

**Issue by HuynhNgoc2709** [Aliucord/hook#8]
hello i know this is just xposed base and users have to add other functions themselves
I have also tried adding loadModule function from xposed api or from pine(PineXposed) but it cannot be loaded
But it's strange that if I use full xposed and core of pine, it can load successfully, so I beg you can help me add that function.
Thank you and wish you good health

**Comment by rushiiMachine** [comment]
> Please note that this is only a partial implementation of Xposed, since we only need method hooking.

If you need to load modules, consider using [LSPatch](https://github.com/LSPosed/LSPatch)

**Comment by HuynhNgoc2709** [comment]
> > Please note that this is only a partial implementation of Xposed, since we only need method hooking.
> 
> If you need to load modules, consider using [LSPatch](https://github.com/LSPosed/LSPatch)

Yes, I know this is just xpose base but I want to both hook and load the module without having to use lspatch
If you have time please help me, Thanks

**Comment by rushiiMachine** [comment]
> I want to both hook and load the module without having to use lspatch

You're looking in the wrong place then, we only support hooking. This is a very minimal wrapper over LSPlant.

**Comment by HuynhNgoc2709** [comment]
Yes, thanks for replying
